### ISSUE TITLE
Numbers cast as strings

### ISSUE THREAD

**Issue by bahmutov** [vkarpov15/archetype-js#4]
using `archetype-js@0.4.2`

```js
const Archetype = require('archetype-js')
const Person = new Archetype({
  name: { $type: 'string', $required: true }
}).compile('Person')
const p = new Person({name: 42})
console.log('person is', p)
```
outputs
```
person is Person { name: '42' }
```

**Comment by vkarpov15** [comment]
Yeah that's by design. If you expect something to be a string, archetype will try to convert it to a string, and will [only refuse to do so if the `toString()` function is the default `Object.prototype.toString()`](https://github.com/vkarpov15/archetype-js/blob/0434ea7bd44ba8313c1216d70c784fffd6b41625/src/to.js#L16-L24). Debatable whether this is correct or not but it's more consistent with the fact that archetype is all about type coercion.
