### ISSUE TITLE
Throw on extra

### ISSUE THREAD

**Issue by riyadhzen** [vkarpov15/archetype-js#6]
Hi. Currently, after defining a schema, if a user enters more fields than what is defined in the schema, the extra fields are dropped silently. Ex:
```
const Person = new Archetype({
  name: 'string',
  bandId: {
    $type: ObjectId,
    $required: true
  },
  createdAt: {
    $type: moment,
    $default: () => moment()
  }
}).compile('Person');

// first client on the website sends this
let userObject = {
  name: 'wagner',
  bandId: '000000000000000000000001',
  isHacker: true
}

let user = new Person(userObject);

// user.isHacker === undefined
```

I wonder if there are any plans to adding the feature of throwing on extra fields like what we currently have with mongoose [strict mode](http://mongoosejs.com/docs/guide.html#strict).
Thanks.

**Comment by vkarpov15** [comment]
No plans to throw on extra fields currently. In our current use case I end up passing certain common fields like the request id header to every function, and having archetype strip it out if it turns out the function doesn't need it.

One potential idea that could help with this though is adding some way to hook into archetypes recursion, so you could execute a function on every field that can throw or whatever. Not a high priority right now though

**Comment by riyadhzen** [comment]
Ok, thanks. awsome work though.
